export type CapsuleProductSeed = {
  catalogNumber: number;
  name: string;
  strength: string;
};

export const CAPSULE_PRODUCT_SEEDS: CapsuleProductSeed[] = [
  { catalogNumber: 1, name: "5-Amino-1mq", strength: "50mg" },
  { catalogNumber: 2, name: "5-Amino-1mq/NMN", strength: "25mg/500mg" },
  { catalogNumber: 3, name: "7-Keto DHEA", strength: "50mg" },
  { catalogNumber: 4, name: "Amino Quad (THE/INO/PRO/TAU)", strength: "50mg/50mg/50mg/50mg" },
  { catalogNumber: 5, name: "Amino-Quad (THE/INO/PRO/TAU)", strength: "50mg/50mg/50mg/50mg" },
  { catalogNumber: 6, name: "Amlexanox", strength: "50mg" },
  { catalogNumber: 7, name: "Amphotericin B", strength: "5mg" },
  { catalogNumber: 8, name: "Anastrozole", strength: "0.25mg" },
  { catalogNumber: 9, name: "Anastrozole Sustained Release", strength: "0.5mg" },
  { catalogNumber: 10, name: "Betahistine Dihydrochloride", strength: "12mg" },
  { catalogNumber: 11, name: "Betamethasone", strength: "0.5mg" },
  { catalogNumber: 12, name: "Betamethasone (BET)", strength: "0.75mg" },
  { catalogNumber: 13, name: "Betamethasone / Gentamicin (BET-G)", strength: "0.75mg/80mg" },
  { catalogNumber: 14, name: "Betamethasone / Gentamicin / Mupirocin (BET-GM)", strength: "0.75mg/80mg/20mg" },
  { catalogNumber: 15, name: "BI-EST (50-50)", strength: "5mg" },
  { catalogNumber: 16, name: "BI-EST (80-20)", strength: "1.25mg" },
  { catalogNumber: 17, name: "Biotin/Minoxidil", strength: "5mg/1.25mg" },
  { catalogNumber: 18, name: "Boric Acid", strength: "600mg" },
  { catalogNumber: 19, name: "BPC-157", strength: "500mcg" },
  { catalogNumber: 20, name: "BPC-157/KPV", strength: "500mcg/500mcg" },
  { catalogNumber: 21, name: "BPC-157 SR", strength: "500mcg" },
  { catalogNumber: 22, name: "Budesonide", strength: "0.5mg" },
  { catalogNumber: 23, name: "Bupropion/Caffeine/Naltrexone/Metformin", strength: "65/20/8/250mg" },
  { catalogNumber: 24, name: "Bupropion/Caff/Nalt/Met/Cyanocobalamin", strength: "65/20/8/250/1mg" },
  { catalogNumber: 25, name: "Bupropion/Methylcobalamin/Metformin", strength: "75mg/1000mcg/100mg" },
  { catalogNumber: 26, name: "Bupropion/Nalt/Met/Cyanocobalamin", strength: "65mg/8mg/250mg/1mg" },
  { catalogNumber: 27, name: "Bupropion/Naltrexone/Metformin", strength: "65mg/8mg/250mg" },
  { catalogNumber: 28, name: "Bupropion/Phen/Nalt/Met/Cyano", strength: "65/20/8/250/1mg" },
  { catalogNumber: 29, name: "Cisapride", strength: "2.5mg" },
  { catalogNumber: 30, name: "Cit/Glu/Lys/Na/Pro/Tau", strength: "50mg/30mg/50mg/1mg/50mg/50mg" },
  { catalogNumber: 31, name: "CIT / GLU / LYS / NAS / PRO / TAU", strength: "50mg/30mg/50mg/1mg/50mg/50mg" },
  { catalogNumber: 32, name: "CLOMIPHENE", strength: "25mg" },
  { catalogNumber: 33, name: "Clomiphene Citrate", strength: "25mg" },
  { catalogNumber: 34, name: "Clomiphene/Resveratrol/B6/ZMA", strength: "12.5mg/50mg/10mg/230mg" },
  { catalogNumber: 35, name: "Danazol", strength: "25mg" },
  { catalogNumber: 36, name: "DHEA", strength: "10mg SR" },
  { catalogNumber: 37, name: "DHEA/Pregnenolone", strength: "50/100mg" },
  { catalogNumber: 38, name: "DHEA (Sustained Release)", strength: "30mg" },
  { catalogNumber: 39, name: "DIHEXA", strength: "5mg" },
  { catalogNumber: 40, name: "Dutasteride (SR)", strength: "0.25mg" },
  { catalogNumber: 41, name: "ECA Stack (High Dose/Low Dose)", strength: "12.5/100/30/0.2/1mg" },
  { catalogNumber: 42, name: "ECA Stack with Yohimbine", strength: "25/200/30/0.2/1/2.75mg" },
  { catalogNumber: 43, name: "Enclomiphene Citrate", strength: "12.5mg" },
  { catalogNumber: 44, name: "ESTRADIOL", strength: "0.75mg" },
  { catalogNumber: 45, name: "Estradiol (Immediate Release)", strength: "0.5mg" },
  { catalogNumber: 46, name: "FIN/B7/Vitamin C", strength: "1mg/2.5mg/100mg" },
  { catalogNumber: 47, name: "Fludrocortisone Acetate", strength: "0.3mg" },
  { catalogNumber: 48, name: "Fluticasone / Gentamicin", strength: "3mg/80mg" },
  { catalogNumber: 49, name: "GHK-Cu (Copper Peptide)", strength: "2mg" },
  { catalogNumber: 50, name: "Glutathione", strength: "200mg" },
  { catalogNumber: 51, name: "Hexarelin", strength: "1mg" },
  { catalogNumber: 52, name: "IBUTAMOREN", strength: "12.5mg" },
  { catalogNumber: 53, name: "Inositol / Naltrexone / Topiramate / Methylcobalamin", strength: "175mg/1mg/25mg/0.25mg" },
  { catalogNumber: 54, name: "Itraconazole", strength: "40mg" },
  { catalogNumber: 55, name: "Ketotifen Fumarate", strength: "1.5mg" },
  { catalogNumber: 56, name: "KYZATREX (ORAL TESTOSTERONE)", strength: "200mg" },
  { catalogNumber: 57, name: "LARAZOTIDE", strength: "250mcg" },
  { catalogNumber: 58, name: "Levofloxacin / Clotrimazole", strength: "100mg/25mg" },
  { catalogNumber: 59, name: "Levofloxacin / Clotrimazole / Fluticasone", strength: "100mg/25mg/3mg" },
  { catalogNumber: 60, name: "Levothyroxine (T4)", strength: "5mcg SR" },
  { catalogNumber: 61, name: "Liothyronine/Levothyroxine (T3 / T4)", strength: "4.5mcg/19mcg SR (0.5 grain)" },
  { catalogNumber: 62, name: "Liothyronine (T3)", strength: "5mcg SR" },
  { catalogNumber: 63, name: "Low-Dose Naltrexone", strength: "1.5mg" },
  { catalogNumber: 64, name: "Methylene Blue", strength: "15mg" },
  { catalogNumber: 65, name: "MIN/B7/Vitamin C", strength: "1mg/2.5mg/100mg" },
  { catalogNumber: 66, name: "MIN/FIN/B7/Vitamin C", strength: "1mg/1mg/2.5mg/100mg" },
  { catalogNumber: 67, name: "Minoxidil", strength: "2.5mg" },
  { catalogNumber: 68, name: "NAD Booster (NMN/RES/QUER/Co-Q10)", strength: "250mg/250mg/250mg/250mg" },
  { catalogNumber: 69, name: "NAD+ (NMN/RES/QUER/Co-Q10)", strength: "250mg/250mg/250mg/250mg" },
  { catalogNumber: 70, name: "Naltrexone", strength: "1mg" },
  { catalogNumber: 71, name: "Oxandrolone", strength: "5mg" },
  { catalogNumber: 72, name: "Paroxetine / Vardenafil", strength: "30mg/20mg" },
  { catalogNumber: 73, name: "Phentermine/Fluoxetine/Chromium", strength: "38mg/10mg/0.2mg" },
  { catalogNumber: 74, name: "Phentermine/Fluoxetine/Chromium/Naltrexone", strength: "38mg/10mg/0.2mg/4.5mg" },
  { catalogNumber: 75, name: "PHENTERMINE HCL", strength: "15mg" },
  { catalogNumber: 76, name: "PHENTERMINE SR", strength: "37.5mg" },
  { catalogNumber: 77, name: "Potassium Bromide", strength: "250mg" },
  { catalogNumber: 78, name: "Pregnenolone", strength: "25mg" },
  { catalogNumber: 79, name: "Progesterone (Immediate Release)", strength: "100mg" },
  { catalogNumber: 80, name: "Progesterone (Modified Release)", strength: "200mg" },
  { catalogNumber: 81, name: "PROGESTERONE SR", strength: "225mg" },
  { catalogNumber: 82, name: "Progesterone (Standard Release)", strength: "500mg" },
  { catalogNumber: 83, name: "PT-141 (Bremelanotide)", strength: "1mg" },
  { catalogNumber: 84, name: "Rapamycin", strength: "5mg" },
  { catalogNumber: 85, name: "Semaglutide/Pyridoxine", strength: "1.5mg/1mg" },
  { catalogNumber: 86, name: "Sermorelin", strength: "500mcg" },
  { catalogNumber: 87, name: "Sildenafil Citrate", strength: "55mg" },
  { catalogNumber: 88, name: "SILDENAFIL SR", strength: "36mg" },
  { catalogNumber: 89, name: "SILDENAFIL/TADALAFIL", strength: "50mg/10mg" },
  { catalogNumber: 90, name: "Sildenafil/Testosterone", strength: "100mg/10mg" },
  { catalogNumber: 91, name: "SLU-PP-332", strength: "250mcg" },
  { catalogNumber: 92, name: "SLU-PP-332/BAM 15", strength: "100mcg/15mg" },
  { catalogNumber: 93, name: "STANOZOLOL", strength: "10mg" },
];
