export type InjectionProductSeed = {
  catalogNumber: number;
  name: string;
  strength: string;
  ordered?: number;
};

export const INJECTION_PRODUCT_SEEDS: InjectionProductSeed[] = [
  { catalogNumber: 1, name: "Tirzepatide/Pyridoxine (B6)", strength: "10mg/2mg/mL", ordered: 612 },
  { catalogNumber: 2, name: "Semaglutide Flex-Dose 4 mL", strength: "2.5 mg/mL", ordered: 282 },
  { catalogNumber: 3, name: "Retatrutide", strength: "16mg/mL", ordered: 73 },
  { catalogNumber: 4, name: "Tirzepatide/Cyanocobalamin (B12)", strength: "15mg/1mg/0.5mL", ordered: 67 },
  { catalogNumber: 5, name: "Nicotinamide Adenine Dinucleotide (NAD+)", strength: "200mg/mL", ordered: 66 },
  { catalogNumber: 6, name: "Sermorelin Acetate", strength: "2mg/mL", ordered: 52 },
  { catalogNumber: 7, name: "Semaglutide/Cyanocobalamin (B12)", strength: "2.5mg/1.25mg/mL", ordered: 48 },
  { catalogNumber: 8, name: "Glutathione", strength: "200mg/mL", ordered: 35 },
  { catalogNumber: 9, name: "Tirzepatide/L-Carnitine", strength: "12.5mg/100mg/mL", ordered: 32 },
  { catalogNumber: 10, name: "BPC-157", strength: "3mg/mL", ordered: 25 },
  { catalogNumber: 11, name: "BPC-157/TB-500 (Wolverine)", strength: "1.66mg/3.33mg/mL", ordered: 18 },
  { catalogNumber: 12, name: "CJC-1295/Ipamorelin", strength: "1.5mg/2.5mg/mL", ordered: 15 },
  { catalogNumber: 13, name: "TB-500", strength: "10mg/3mL", ordered: 13 },
  { catalogNumber: 14, name: "GHK-Cu (Copper Peptide)", strength: "10mg/mL", ordered: 12 },
  { catalogNumber: 15, name: "Tirzepatide/NAD+/L-Carnitine", strength: "15mg/40mg/250mg/mL", ordered: 12 },
  { catalogNumber: 16, name: "Tirzepatide (sic)", strength: "10mg/mL", ordered: 12 },
  { catalogNumber: 17, name: "Ascorbic Acid (Tapioca Base) Vitamin C", strength: "500mg/mL", ordered: 11 },
  { catalogNumber: 18, name: "Ascorbic Acid (Vitamin C)", strength: "[5500mg] 550mg/mL", ordered: 8 },
  { catalogNumber: 19, name: "Semaglutide/Glycine", strength: "2.5mg/7.5mg/mL", ordered: 7 },
  { catalogNumber: 20, name: "Testosterone Cypionate (Commercial)", strength: "200mg/mL", ordered: 7 },
  { catalogNumber: 21, name: "GHK-Cu/BPC-157/TB-500 (Glow)", strength: "9mg/1.66mg/3.33mg/mL", ordered: 6 },
  { catalogNumber: 22, name: "N-Acetyl-L-Cysteine", strength: "200mg/mL", ordered: 6 },
  { catalogNumber: 23, name: "Semaglutide/NAD+", strength: "1mg/20mg/mL", ordered: 6 },
  { catalogNumber: 24, name: "Sermorelin", strength: "3mg/mL", ordered: 6 },
  { catalogNumber: 25, name: "Tesamorelin/Ipamorelin", strength: "2.4mg/1.2mg/mL", ordered: 6 },
  { catalogNumber: 26, name: "Testosterone Cypionate in Sesame Seed Oil", strength: "200mg", ordered: 6 },
  { catalogNumber: 27, name: "Testosterone Cypionate Miglyol 812N Oil", strength: "200mg/mL", ordered: 6 },
  { catalogNumber: 28, name: "Vitamin B12", strength: "1mg/mL", ordered: 6 },
  { catalogNumber: 29, name: "Aminoblend", strength: "100/50/50/50/100 mg/mL", ordered: 4 },
  { catalogNumber: 30, name: "BPC/157/TB500/KPV/GHK/CU", strength: "3/3/3/10 mg/mL", ordered: 4 },
  { catalogNumber: 31, name: "Magnesium Sulfate", strength: "500mg/mL", ordered: 4 },
  { catalogNumber: 32, name: "Tesamorelin", strength: "2mg/mL", ordered: 4 },
  { catalogNumber: 33, name: "Tirzepatide/Niacinamide", strength: "20mg/25mg/mL", ordered: 4 },
  { catalogNumber: 34, name: "Alpha Lipoic Acid", strength: "25mg/mL", ordered: 3 },
  { catalogNumber: 35, name: "Glycine", strength: "50mg/mL", ordered: 3 },
  { catalogNumber: 36, name: "Gonadorelin Acetate", strength: "1mg", ordered: 3 },
  { catalogNumber: 37, name: "Levocarnitine", strength: "500mg/mL", ordered: 3 },
  { catalogNumber: 38, name: "Mots-C", strength: "10mg/mL", ordered: 3 },
  { catalogNumber: 39, name: "Tirzepatide/Glycine", strength: "16.6mg/7.5mg/mL", ordered: 3 },
  { catalogNumber: 40, name: "Zinc Chloride", strength: "10mg/mL", ordered: 3 },
  { catalogNumber: 41, name: "Biotin (Vitamin B7)", strength: "10mg/mL", ordered: 2 },
  { catalogNumber: 42, name: "Melanotan II", strength: "2mg/mL", ordered: 2 },
  { catalogNumber: 43, name: "Methylcobalamin", strength: "5mg/mL", ordered: 2 },
  { catalogNumber: 44, name: "MIC", strength: "25mg/50mg/50mg/mL", ordered: 2 },
  { catalogNumber: 45, name: "Semaglutide/L-Carnitine", strength: "2.5mg/100mg/mL", ordered: 2 },
  { catalogNumber: 46, name: "Sodium Ascorbate", strength: "500mg/mL", ordered: 2 },
  { catalogNumber: 47, name: "Sodium Ascorbate (PF)", strength: "500mg/mL", ordered: 2 },
  { catalogNumber: 48, name: "Taurine", strength: "50mg/mL", ordered: 2 },
  { catalogNumber: 49, name: "Testosterone Cypionate (Sesame Seed Oil)", strength: "200mg/mL", ordered: 2 },
  { catalogNumber: 50, name: "Tri-Mix (PGE/PAPA/PHEN)", strength: "10mcg/30mg/1mg/mL", ordered: 2 },
  { catalogNumber: 51, name: "BPC/157/TB500/KPV (NO COPPER)", strength: "3/3/3 mg/mL" },
  { catalogNumber: 52, name: "Elamipretide (SS31)", strength: "15mg/mL" },
  { catalogNumber: 53, name: "Hydrogen Peroxide", strength: "3%" },
  { catalogNumber: 54, name: "Lipoden Skinny Shot", strength: "50/5/50/5/5/1/12.5/25/50/10/50 mg/mL" },
  { catalogNumber: 55, name: "Methionine/Inositol/Choline Chloride/Methylcobalamin", strength: "15mg/50mg/100mg/1mg/mL" },
  { catalogNumber: 56, name: "MIC/B12", strength: "25/100/50/1 mg/mL" },
  { catalogNumber: 57, name: "Phosphatidylcholine/Deoxycholic Acid (PCDC)", strength: "100mg/47.5mg/mL" },
  { catalogNumber: 58, name: "Pregnyl HCG (Commercial)", strength: "10000IU/vial" },
  { catalogNumber: 59, name: "Theanine", strength: "50mg/mL" },
  { catalogNumber: 60, name: "Tripeptide-1 (GHK-Cu)", strength: "10mg/mL" },
  { catalogNumber: 61, name: "5-Amino-1MQ", strength: "5mg/mL" },
  { catalogNumber: 62, name: "Alprostadil/Papaverine HCl/Phentolamine Mesylate", strength: "10mcg/30mg/1mg/mL" },
  { catalogNumber: 63, name: "Amino Acid #1", strength: "75/25/15/30/15/30/50/5/10/25 mg/mL" },
  { catalogNumber: 64, name: "Amino Acid #3", strength: "25/5/5/2.5/4/5/1/5/10/25 mg/mL" },
  { catalogNumber: 65, name: "AOD-9604", strength: "1.2mg/mL" },
  { catalogNumber: 66, name: "AOD-9604/MOTS-C/Tesamorelin/Ipamorelin", strength: "1.2/2/2/2 mg/mL" },
  { catalogNumber: 67, name: "ARA 290", strength: "6mg/mL" },
  { catalogNumber: 68, name: "Arginine", strength: "[7500mg] 200mg/mL" },
  { catalogNumber: 69, name: "Ascorbic Acid", strength: "500mg/mL" },
  { catalogNumber: 70, name: "B-Complex", strength: "25/25/25/2/2 mg/mL" },
  { catalogNumber: 71, name: "Bimix (PAPA/PHEN)", strength: "[150mg/5mg] 30mg/1mg/mL" },
  { catalogNumber: 72, name: "Branched Chain Amino Acids (BCAA) (ILE/L/V)", strength: "0.4/0.3/1.2 gm/mL" },
  { catalogNumber: 73, name: "Bremelanotide Acetate (PT-141)", strength: "10mg/mL" },
  { catalogNumber: 74, name: "Calcium Gluconate", strength: "10%" },
  { catalogNumber: 75, name: "Cartalax (AED, T-31)", strength: "4mg/mL" },
  { catalogNumber: 76, name: "Coenzyme Q10", strength: "25mg/mL" },
  { catalogNumber: 77, name: "Dexpanthenol", strength: "250mg/mL" },
  { catalogNumber: 78, name: "DSIP", strength: "2mg/mL" },
  { catalogNumber: 79, name: "Dutasteride", strength: "100mcg/mL" },
  { catalogNumber: 80, name: "Epithalon", strength: "2mg/mL" },
  { catalogNumber: 81, name: "Folic Acid", strength: "10mg/mL" },
  { catalogNumber: 82, name: "FOXO4-DRI", strength: "2mg/mL" },
  { catalogNumber: 83, name: "GHK/CU/Epithalon", strength: "10/2 mg/mL" },
  { catalogNumber: 84, name: "Glycerin", strength: "72%" },
  { catalogNumber: 85, name: "Gonadorelin", strength: "200mcg/mL" },
  { catalogNumber: 86, name: "IGF-LR3", strength: "200mcg/mL" },
  { catalogNumber: 87, name: "Kisspeptin", strength: "1mg/mL" },
  { catalogNumber: 88, name: "L-Carnitine", strength: "500mg/mL" },
  { catalogNumber: 89, name: "Lidocaine", strength: "2% (20mg/mL)" },
  { catalogNumber: 90, name: "LIPO-B (Cyanocobalamin/MIC)", strength: "25mg/50mg/50mg/1mg/mL" },
  { catalogNumber: 91, name: "Lipo-C", strength: "25/25/50/100/1 mg/mL" },
  { catalogNumber: 92, name: "LIPO-C (Cyanocobalamin/MIC/L-Carnitine)", strength: "15mg/50mg/50mg/mL" },
  { catalogNumber: 93, name: "Liraglutide", strength: "12mg/mL" },
  { catalogNumber: 94, name: "Liraglutide/Methionine", strength: "6mg/2mg/mL" },
  { catalogNumber: 95, name: "LL-37", strength: "1mg/mL" },
  { catalogNumber: 96, name: "L-Leucine/L-Isoleucine/L-Valine", strength: "10mg/10mg/5mg/mL" },
  { catalogNumber: 97, name: "Lysine", strength: "200mg/mL" },
  { catalogNumber: 98, name: "Myer's Cocktail", strength: "100mg/10mg/0.5mg/mL" },
  { catalogNumber: 99, name: "Nandrolone", strength: "200mg/mL" },
  { catalogNumber: 100, name: "Nandrolone Decanoate", strength: "200mg/mL" },
  { catalogNumber: 101, name: "Nandrolone Decanoate (Sesame Oil)", strength: "200mg/mL" },
  { catalogNumber: 102, name: "Nandrolone Grape Seed Oil", strength: "200mg/mL" },
  { catalogNumber: 103, name: "Oxytocin", strength: "100IU/mL" },
  { catalogNumber: 104, name: "PEG-MGF", strength: "0.4mg/mL" },
  { catalogNumber: 105, name: "Pentadecapeptide Arginate (PDA)", strength: "10mg/mL" },
  { catalogNumber: 106, name: "Phenylephrine", strength: "10mg/mL" },
  { catalogNumber: 107, name: "Procaine", strength: "2%" },
  { catalogNumber: 108, name: "Proline", strength: "50mg/mL" },
  { catalogNumber: 109, name: "PT/141", strength: "2mg/mL" },
  { catalogNumber: 110, name: "Pyridoxine (Vitamin B6)", strength: "100mg/mL" },
  { catalogNumber: 111, name: "Quadmix (PAPA/PHEN/ATRO/PGE)", strength: "9mg/1mg/10mcg/10mcg/mL" },
  { catalogNumber: 112, name: "Semaglutide/Glycine/B12", strength: "1mg/1mg/10mg/mL" },
  { catalogNumber: 113, name: "Sermorelin/Ipamorelin", strength: "3mg/3.6mg/mL" },
  { catalogNumber: 114, name: "Sodium Deoxycholate", strength: "1.67%" },
  { catalogNumber: 115, name: "Testosterone Cyp Grape Seed Oil", strength: "200mg/mL" },
  { catalogNumber: 116, name: "Testosterone Ent Grape Seed Oil", strength: "200mg/mL" },
  { catalogNumber: 117, name: "Testosterone Pro Grape Seed Oil", strength: "100mg/mL" },
  { catalogNumber: 118, name: "Testosterone (Various Female Esters & Blends)", strength: "Cypionate/Propionate 175mg/25mg/mL" },
  { catalogNumber: 119, name: "Test Product 2", strength: "10mg/2.5mg/mL" },
  { catalogNumber: 120, name: "Thymosin Alpha-1", strength: "3mg/mL" },
  { catalogNumber: 121, name: "Tirzepatide/Glycine/B12", strength: "10mg/5mg/500mcg/mL" },
  { catalogNumber: 122, name: "Vitamin B-12 (Cyanocobalamin)", strength: "1200mg/mL" },
  { catalogNumber: 123, name: "Vitamin D3", strength: "50,000IU/mL" },
];
